### ISSUE TITLE
[Feature request] Ability to add more than one instance of a tile

### ISSUE THREAD

**Issue by HulkSmashBurgers** [TilesOrganization/support#17]
For example, I have a power tile that restarts. I would also like to add a power tile that reboots to recovery.

**Comment by rascarlo** [comment]
hi @unknownsoldierx and thanks for opening a new issue. Having the option to add more than one instance of a tile won't be added since the component can not be created at runtime but needs to be in the code. Apps, activities, shortcuts come with up to five tiles, but the same won't apply to the power tile
