### ISSUE TITLE
Feature Req: Long Press - Secondary Action

### ISSUE THREAD

**Issue by NeoBeum** [TilesOrganization/support#6]
Unless I've missed it and it's already implemented.

A long press on icon for second action would be great

**Comment by rascarlo** [comment]
Hi @NeoBeum and thanks for opening the issue.
Unfortunately a long press event is not exposed by the API [1].

The long press action is optional but recommended [2].

> An activity that provides a user interface for adjusting TileService preferences. Optional but recommended for apps that implement a TileService. 

[1] https://developer.android.com/reference/android/service/quicksettings/Tile.html
[2] https://developer.android.com/reference/android/service/quicksettings/TileService.html#ACTION_QS_TILE_PREFERENCES

**Comment by rascarlo** [comment]
Closing the issue as invalid

**Comment by NeoBeum** [comment]
@rascarlo Ah ok, thanks.  Are there any incompatible changes to QS API for SDK24  to SDK26 that you know of?   The quick settings for system apps are not quick anymore for Xperias. I was going to look at porting the menu for Oreo or other Manufacturers. I feel sorry for iOS, where users only disconnect connected radio if toggled from quick settings, and they need to go into main menu to turn off or turn on the services.

**Comment by rascarlo** [comment]
@NeoBeum unfortunately nothing has changed in the quick settings tiles [1] and the quick settings tile service [2] APIs, and the documentation hasn't changed either. About experia implementation, that is a completely different case since they build from source and they can inject any code they want and edit the master code.

[1] https://developer.android.com/reference/android/service/quicksettings/Tile.html
[2] https://developer.android.com/reference/android/service/quicksettings/TileService.html
